initial_screen = "queue"
flip_status_indicators = true
album_column = false

[theme]
title = "#aaa"
highlight_bg = "#444"
cmdline = "red"
cmdline_bg = "black"
error = "red"
error_bg = "black"
statusbar = "blue"

[track_format]
left = "%artists - %title"
center = ""
